# Generated by Django 5.1 on 2024-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_id', models.IntegerField()),
                ('c_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('Address', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('fuelType', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('ownership', models.CharField(max_length=50)),
                ('kmDriven', models.IntegerField()),
                ('engineCapacity', models.IntegerField()),
                ('makeYear', models.IntegerField()),
                ('regNumber', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bookcar',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
