# Generated by Django 5.1 on 2024-09-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sellcar_bookcar_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='C_id',
        ),
    ]
