# Generated by Django 5.1 on 2024-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_sellcar_c_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='engineCapacity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='kmDriven',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='makeYear',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='seats',
            field=models.CharField(max_length=50),
        ),
    ]
