# Generated by Django 5.1 on 2024-09-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sellcar_enginecapacity_alter_sellcar_kmdriven_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellCar',
        ),
    ]
