# Generated by Django 5.1 on 2024-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_sellcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('car_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('seats', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('ownership', models.CharField(max_length=50)),
                ('km_driven', models.CharField(max_length=50)),
                ('engine_capacity', models.CharField(max_length=50)),
                ('make_year', models.CharField(max_length=50)),
                ('reg_number', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
