# Generated by Django 5.1 on 2024-09-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sellcar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcar',
            old_name='fuelType',
            new_name='car_name',
        ),
        migrations.RenameField(
            model_name='bookcar',
            old_name='name',
            new_name='engine_capacity',
        ),
        migrations.RenameField(
            model_name='bookcar',
            old_name='regNumber',
            new_name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='engineCapacity',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='kmDriven',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='makeYear',
        ),
        migrations.AddField(
            model_name='bookcar',
            name='km_driven',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookcar',
            name='make_year',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookcar',
            name='reg_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookcar',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookcar',
            name='seats',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
