# Generated by Django 5.1 on 2024-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reservation_rescreated_reservation_resdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('calories', models.CharField(max_length=50)),
                ('protein', models.CharField(max_length=50)),
                ('fat', models.CharField(max_length=50)),
                ('carbs', models.CharField(max_length=50)),
            ],
        ),
    ]
