# Generated by Django 5.0.4 on 2024-09-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cart_image_cart_quantity_alter_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=10)),
                ('table_number', models.PositiveIntegerField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='resPhone',
            field=models.CharField(max_length=10),
        ),
    ]
